##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
    tasks:
        - export DEPLOYPATH=/home/students/public_html/ignite
        - /bin/cp tailwind.config.js $DEPLOYPATH
        - /bin/cp server.js $DEPLOYPATH
        - /bin/cp postcss.config.js $DEPLOYPATH
        - /bin/cp package.json $DEPLOYPATH
        - /bin/cp package-lock.json $DEPLOYPATH
        - /bin/cp next.config.js $DEPLOYPATH
        - /bin/cp .eslintrc.json $DEPLOYPATH
        - /bin/cp .cpanel.yml $DEPLOYPATH
        - /bin/cp -R styles $DEPLOYPATH
        - /bin/cp -R src $DEPLOYPATH
        - /bin/cp -R public $DEPLOYPATH
        - /bin/cp -R pages $DEPLOYPATH
        # - /bin/cp -R img $DEPLOYPATH
        - /bin/cp -R .next $DEPLOYPATH
