const EVENTS = [
	{
		id: 0,
		name: "Silent DJ",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/icons/1.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 1,
		name: "URL Human Chain",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/icons/2.png",
		backgroundColor: "",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 2,
		name: "NFT Airdrop",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/icons/3.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 3,
		name: "Tic Tac Toe (4x4)",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/icons/4.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 4,
		name: "Scratch-based game building",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/icons/5.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
];

export default EVENTS;
